### ISSUE TITLE
Testing Feedback/Issues

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_truckrobbery#10]
### The problem

- bomb instantly blows up after being placed
- other players can't loot the truck, only the player who blew it up
- no notification when getting the mission, only sent to phone

### Ideal solution

- config option for a list of item rewards instead of hard coding money reward, each item reward should have a probability of being in the back of the truck, and a separate config option for how many to select
- config option for the bomb item required (so servers can pick different items)

### Additional context

Some enhancements would be to put some guys in the back of the truck that you have to defeat once the door is blown and also to tweak the AI behavior not to stop, get out and shoot at players right away but maybe to try to drive away?

**Comment by TonybynMp4** [comment]
Also, when joining the server the ped isn't there, you gotta restart the resource
