### ISSUE TITLE
Network Interactions

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qbx_truckrobbery#6]
### The problem

Only the person who starts the mission can interact with the mission. Get the notifications, plant the bomb, loot the truck.

### Ideal solution

Add the same ox_target options for everyone in the server. The notifications would require knowing who is in the group of the heist. A simple way to do that is to do notifications for anyone near the player who started the mission. Or integration with group based job/crime systems. Syncing the notifications is perhaps less important than the actual interactions.

Doing this will also require careful editing to prevent multiple players from undertaking the same action at the same time, such as planting a bomb, or looting the truck. The server will have to keep players in sync, and edge cases such as players joining the server after the mission has started will need to be taken into account.

**Comment by TonybynMp4** [comment]
qbx_groups soon™️

**Comment by jellyton69** [comment]
Perhaps a state bag on the truck? 

It would handle the syncing of the truck's loot state automatically, we wouldn't need to network anything to the entire server, and it would be easy to handle the actual interaction point by doing the work in a state change handler.

**Comment by Manason** [comment]
> Perhaps a state bag on the truck?
> 
> It would handle the syncing of the truck's loot state automatically, we wouldn't need to network anything to the entire server, and it would be easy to handle the actual interaction point by doing the work in a state change handler.

Yeah that's a perfect idea. This is a great use case for state bags.
